### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by aezarebski** [vrom911/common-stanzas-example#1]
Thanks for the great explanation this was really helpful.

There are a couple of broken links. I think these are the appropriate links now:

- https://cabal.readthedocs.io/developing-packages.html#pkg-desc --> https://cabal.readthedocs.io/en/3.4/cabal-package.html
- https://cabal.readthedocs.io/developing-packages.html#common-stanzas --> https://cabal.readthedocs.io/en/3.4/cabal-package.html?highlight=common#common-stanzas
- https://cabal.readthedocs.io/developing-packages.html#using-cabal-init --> https://cabal.readthedocs.io/en/3.4/developing-packages.html?highlight=use%20init#using-cabal-init

**Comment by vrom911** [comment]
Thanks a lot for reporting! 🤗 
All these links indeed were changed in Cabal. I am fixing this in https://github.com/vrom911/vrom911.github.io/pull/60

**Comment by vrom911** [comment]
This is fixed now. Thanks again! 👍🏼

**Comment by aezarebski** [comment]
Thanks for writing the post!
